// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:weex_flutter_demo/weex_flutter/annotation/reflector.dart'
    as prefix0;
import 'package:weex_flutter_demo/weex_flutter/model/wx_js_callback.dart'
    as prefix4;
import 'package:weex_flutter_demo/weex_flutter/module/wx_navigate.dart'
    as prefix3;
import 'package:weex_flutter_demo/weex_flutter/module/wx_storage.dart'
    as prefix1;
import 'package:weex_flutter_demo/weex_flutter/module/wx_system.dart'
    as prefix2;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'WXStorage',
            r'.WXStorage',
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 3, 4, 5],
            const <int>[6, 7, 8, 9, 10, 0, 1, 2, 3, 4],
            const <int>[],
            -1,
            {},
            {},
            {r'': (b) => () => b ? prefix1.WXStorage() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'WXSystem',
            r'.WXSystem',
            7,
            1,
            const prefix0.Reflector(),
            const <int>[11, 12],
            const <int>[6, 7, 8, 9, 10, 11],
            const <int>[],
            -1,
            {},
            {},
            {r'': (b) => () => b ? prefix2.WXSystem() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null),
        r.NonGenericClassMirrorImpl(
            r'WXNavigate',
            r'.WXNavigate',
            7,
            2,
            const prefix0.Reflector(),
            const <int>[13, 14, 15],
            const <int>[6, 7, 8, 9, 10, 13, 14],
            const <int>[],
            -1,
            {},
            {},
            {r'': (b) => () => b ? prefix3.WXNavigate() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        r.MethodMirrorImpl(r'setItem', 262146, 0, null, 3, 3, null,
            const <int>[0, 1, 2], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'getItem', 262146, 0, null, 3, 3, null,
            const <int>[3, 4], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'removeItem', 262146, 0, null, 3, 3, null,
            const <int>[5, 6], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'getAllKeys', 262146, 0, null, 3, 3, null,
            const <int>[7], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'clear', 262146, 0, null, 3, 3, null,
            const <int>[8], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'', 64, 0, -1, 0, 0, null, const <int>[],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 4, 4, null, const <int>[9],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 5, 5, null,
            const <int>[], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, null, null, null, null, null,
            const <int>[10], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 6, 6, null,
            const <int>[], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'runtimeType', 131075, null, -1, 7, 7, null,
            const <int>[], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'requestFocus', 262146, 1, null, 3, 3, null,
            const <int>[11], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'', 64, 1, -1, 1, 1, null, const <int>[],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'push', 262146, 2, null, 3, 3, null,
            const <int>[12, 13], const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'pop', 262146, 2, null, 3, 3, null, const <int>[14],
            const prefix0.Reflector(), null),
        r.MethodMirrorImpl(r'', 64, 2, -1, 2, 2, null, const <int>[],
            const prefix0.Reflector(), null)
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'key', 32774, 0, const prefix0.Reflector(), -1,
            5, 5, null, null, null, null),
        r.ParameterMirrorImpl(r'value', 32774, 0, const prefix0.Reflector(), -1,
            5, 5, null, null, null, null),
        r.ParameterMirrorImpl(r'callback', 32774, 0, const prefix0.Reflector(),
            -1, 8, 8, null, null, null, null),
        r.ParameterMirrorImpl(r'key', 32774, 1, const prefix0.Reflector(), -1,
            5, 5, null, null, null, null),
        r.ParameterMirrorImpl(r'callback', 32774, 1, const prefix0.Reflector(),
            -1, 8, 8, null, null, null, null),
        r.ParameterMirrorImpl(r'key', 32774, 2, const prefix0.Reflector(), -1,
            5, 5, null, null, null, null),
        r.ParameterMirrorImpl(r'callback', 32774, 2, const prefix0.Reflector(),
            -1, 8, 8, null, null, null, null),
        r.ParameterMirrorImpl(r'callback', 32774, 3, const prefix0.Reflector(),
            -1, 8, 8, null, null, null, null),
        r.ParameterMirrorImpl(r'callback', 32774, 4, const prefix0.Reflector(),
            -1, 8, 8, null, null, null, null),
        r.ParameterMirrorImpl(r'other', 32774, 6, const prefix0.Reflector(), -1,
            9, 9, null, null, null, null),
        r.ParameterMirrorImpl(r'invocation', 32774, 8,
            const prefix0.Reflector(), -1, 10, 10, null, null, null, null),
        r.ParameterMirrorImpl(r'callback', 32774, 11, const prefix0.Reflector(),
            -1, 8, 8, null, null, null, null),
        r.ParameterMirrorImpl(r'model', 2129926, 13, const prefix0.Reflector(),
            -1, 11, 12, null, null, null, null),
        r.ParameterMirrorImpl(r'callback', 32774, 13, const prefix0.Reflector(),
            -1, 8, 8, null, null, null, null),
        r.ParameterMirrorImpl(r'callback', 32774, 14, const prefix0.Reflector(),
            -1, 8, 8, null, null, null, null)
      ],
      <Type>[
        prefix1.WXStorage,
        prefix2.WXSystem,
        prefix3.WXNavigate,
        const m.TypeValue<void>().type,
        bool,
        String,
        int,
        Type,
        prefix4.WXJSCallback,
        Object,
        Invocation,
        const m.TypeValue<Map<dynamic, dynamic>>().type,
        Map
      ],
      3,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'setItem': (dynamic instance) => instance.setItem,
        r'getItem': (dynamic instance) => instance.getItem,
        r'removeItem': (dynamic instance) => instance.removeItem,
        r'getAllKeys': (dynamic instance) => instance.getAllKeys,
        r'clear': (dynamic instance) => instance.clear,
        r'requestFocus': (dynamic instance) => instance.requestFocus,
        r'push': (dynamic instance) => instance.push,
        r'pop': (dynamic instance) => instance.pop
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
